apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    app: kafka-cluster
spec:
  type: NodePort
  ports:
  - port: 9091
    name: kafka01
    targetPort: 9091
    nodePort: 32091
    protocol: TCP
  - port: 9092
    name: kafka02
    targetPort: 9092
    nodePort: 32092
    protocol: TCP
  - port: 9093
    name: kafka03
    targetPort: 9093
    nodePort: 32093
    protocol: TCP
  selector:
    app: kafka-cluster
