apiVersion: v1
kind: Service
metadata:
    name: kafkalocal
    labels:
        event-gateway: kafka
        type: eg
spec:
    ports:
        - protocol: TCP
          name: kafka01
          port: 9092
          targetPort: 9092
        - protocol: TCP
          name: kafka02
          port: 9093
          targetPort: 9093
        - protocol: TCP
          name: kafka03
          port: 9094
          targetPort: 9094
---
apiVersion: v1
kind: Endpoints
metadata:
    name: kafkalocal
    labels:
        event-gateway: kafka
        type: eg
subsets:
    - addresses:
        - ip: 192.168.49.2
      ports:
        - port: 9092
          name: kafka01
        - port: 9093
          name: kafka02
        - port: 9094
          name: kafka03

---
apiVersion: v1
kind: Service
metadata:
    name: zoolocal
spec:
    ports:
        - protocol: TCP
          port: 2181
          targetPort: 2181
---
apiVersion: v1
kind: Endpoints
metadata:
    name: zoolocal
subsets:
    - addresses:
        - ip: 192.168.49.2
      ports:
        - port: 2181
---
apiVersion: v1
kind: Service
metadata:
    name: schemalocal
spec:
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
---
apiVersion: v1
kind: Endpoints
metadata:
    name: schemalocal
subsets:
    - addresses:
        - ip: 192.168.49.2
      ports:
        - port: 8081
