apiVersion: v1
kind: Service
metadata:
  name: kafka01
  labels:
    app: kafka01
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kafka01
    targetPort: 9092
    nodePort: 32091
    protocol: TCP
  selector:
    app: kafka-cluster
