apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
spec:
  containers:
  - image: confluent/zookeeper:latest
    name: zookeeper
    ports:
    - containerPort: 2181
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "YES"

  - image: confluent/kafka:latest
    name: kafka01
    env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://:9092"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-cluster:9092"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka-cluster
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "kafka-cluster:2181"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "TRUE"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    ports:
    - containerPort: 9092
      protocol: TCP

  - image: confluent/kafka:latest
    name: kafka02
    env:
    - name: KAFKA_BROKER_ID
      value: "2"
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://:9093"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-cluster:9093"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka-cluster
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "kafka-cluster:2181"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "TRUE"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    ports:
    - containerPort: 9093
      protocol: TCP

  - image: confluent/kafka:latest
    name: kafka03
    env:
    - name: KAFKA_BROKER_ID
      value: "3"
    - name: KAFKA_LISTENERS
      value: "PLAINTEXT://:9094"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-cluster:9094"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka-cluster
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "kafka-cluster:2181"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "TRUE"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    ports:
    - containerPort: 9094
      protocol: TCP
