apiVersion: v1
kind: Service
metadata:
  name: nfl-processor
  labels:
    app: nfl-processor
spec:
  type: NodePort
  ports:
  - port: 18080
    name: metrics
    targetPort: 18080
 #   nodePort: 38080
    protocol: TCP
  selector:
    app: nfl-processor
